package com.htc.jbpm.reclamos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReclamoDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String codCliente;
   private java.util.Date fechaReclamo;

   private java.math.BigDecimal montoCompra;

   private java.lang.Boolean fechaCompraValida;

   public ReclamoDTO()
   {
   }

   public java.lang.String getCodCliente()
   {
      return this.codCliente;
   }

   public void setCodCliente(java.lang.String codCliente)
   {
      this.codCliente = codCliente;
   }

   public java.util.Date getFechaReclamo()
   {
      return this.fechaReclamo;
   }

   public void setFechaReclamo(java.util.Date fechaReclamo)
   {
      this.fechaReclamo = fechaReclamo;
   }

   public java.math.BigDecimal getMontoCompra()
   {
      return this.montoCompra;
   }

   public void setMontoCompra(java.math.BigDecimal montoCompra)
   {
      this.montoCompra = montoCompra;
   }

   public java.lang.Boolean getFechaCompraValida()
   {
      return this.fechaCompraValida;
   }

   public void setFechaCompraValida(java.lang.Boolean fechaCompraValida)
   {
      this.fechaCompraValida = fechaCompraValida;
   }

   public ReclamoDTO(java.lang.String codCliente, java.util.Date fechaReclamo,
         java.math.BigDecimal montoCompra, java.lang.Boolean fechaCompraValida)
   {
      this.codCliente = codCliente;
      this.fechaReclamo = fechaReclamo;
      this.montoCompra = montoCompra;
      this.fechaCompraValida = fechaCompraValida;
   }

}