package com.htc.jbpm.reclamos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class reclamoWS implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String numCuenta;
   private java.lang.String codCliente;
   private java.lang.String monto;
   private java.util.Date fechaCompra;

   public reclamoWS()
   {
   }

   public java.lang.String getNumCuenta()
   {
      return this.numCuenta;
   }

   public void setNumCuenta(java.lang.String numCuenta)
   {
      this.numCuenta = numCuenta;
   }

   public java.lang.String getCodCliente()
   {
      return this.codCliente;
   }

   public void setCodCliente(java.lang.String codCliente)
   {
      this.codCliente = codCliente;
   }

   public java.lang.String getMonto()
   {
      return this.monto;
   }

   public void setMonto(java.lang.String monto)
   {
      this.monto = monto;
   }

   public java.util.Date getFechaCompra()
   {
      return this.fechaCompra;
   }

   public void setFechaCompra(java.util.Date fechaCompra)
   {
      this.fechaCompra = fechaCompra;
   }

   public reclamoWS(java.lang.String numCuenta, java.lang.String codCliente,
         java.lang.String monto, java.util.Date fechaCompra)
   {
      this.numCuenta = numCuenta;
      this.codCliente = codCliente;
      this.monto = monto;
      this.fechaCompra = fechaCompra;
   }

}