package com.htc.jbpm.reclamos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReclamoDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String codCliente;
   private java.lang.String numVoucher;

   public ReclamoDTO()
   {
   }

   public java.lang.String getCodCliente()
   {
      return this.codCliente;
   }

   public void setCodCliente(java.lang.String codCliente)
   {
      this.codCliente = codCliente;
   }

   public java.lang.String getNumVoucher()
   {
      return this.numVoucher;
   }

   public void setNumVoucher(java.lang.String numVoucher)
   {
      this.numVoucher = numVoucher;
   }

   public ReclamoDTO(java.lang.String codCliente, java.lang.String numVoucher)
   {
      this.codCliente = codCliente;
      this.numVoucher = numVoucher;
   }

}