package com.htc.jbpm.reclamos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReclamoDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String codCliente;
   private java.lang.String numVoucher;

   private java.util.Date fechaReclamo;

   private java.math.BigDecimal montoCompra;

   public ReclamoDTO()
   {
   }

   public java.lang.String getCodCliente()
   {
      return this.codCliente;
   }

   public void setCodCliente(java.lang.String codCliente)
   {
      this.codCliente = codCliente;
   }

   public java.lang.String getNumVoucher()
   {
      return this.numVoucher;
   }

   public void setNumVoucher(java.lang.String numVoucher)
   {
      this.numVoucher = numVoucher;
   }

   public java.util.Date getFechaReclamo()
   {
      return this.fechaReclamo;
   }

   public void setFechaReclamo(java.util.Date fechaReclamo)
   {
      this.fechaReclamo = fechaReclamo;
   }

   public java.math.BigDecimal getMontoCompra()
   {
      return this.montoCompra;
   }

   public void setMontoCompra(java.math.BigDecimal montoCompra)
   {
      this.montoCompra = montoCompra;
   }

   public ReclamoDTO(java.lang.String codCliente, java.lang.String numVoucher,
         java.util.Date fechaReclamo, java.math.BigDecimal montoCompra)
   {
      this.codCliente = codCliente;
      this.numVoucher = numVoucher;
      this.fechaReclamo = fechaReclamo;
      this.montoCompra = montoCompra;
   }

}