package com.htc.jbpm.reclamos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitudCredito implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Encargado")
   private java.lang.String nombreSuperior;
   @org.kie.api.definition.type.Label(value = "Credito a favor de")
   private java.lang.String solicitanteCredito;
   @org.kie.api.definition.type.Label(value = "numero de cuenta")
   private java.lang.String numeroCuenta;
   @org.kie.api.definition.type.Label(value = "Monto ")
   private java.math.BigDecimal monto;
   @org.kie.api.definition.type.Label(value = "Por concepto de:")
   private java.lang.String concepto;

   public SolicitudCredito()
   {
   }

   public java.lang.String getNombreSuperior()
   {
      return this.nombreSuperior;
   }

   public void setNombreSuperior(java.lang.String nombreSuperior)
   {
      this.nombreSuperior = nombreSuperior;
   }

   public java.lang.String getSolicitanteCredito()
   {
      return this.solicitanteCredito;
   }

   public void setSolicitanteCredito(java.lang.String solicitanteCredito)
   {
      this.solicitanteCredito = solicitanteCredito;
   }

   public java.lang.String getNumeroCuenta()
   {
      return this.numeroCuenta;
   }

   public void setNumeroCuenta(java.lang.String numeroCuenta)
   {
      this.numeroCuenta = numeroCuenta;
   }

   public java.math.BigDecimal getMonto()
   {
      return this.monto;
   }

   public void setMonto(java.math.BigDecimal monto)
   {
      this.monto = monto;
   }

   public java.lang.String getConcepto()
   {
      return this.concepto;
   }

   public void setConcepto(java.lang.String concepto)
   {
      this.concepto = concepto;
   }

   public SolicitudCredito(java.lang.String nombreSuperior,
         java.lang.String solicitanteCredito, java.lang.String numeroCuenta,
         java.math.BigDecimal monto, java.lang.String concepto)
   {
      this.nombreSuperior = nombreSuperior;
      this.solicitanteCredito = solicitanteCredito;
      this.numeroCuenta = numeroCuenta;
      this.monto = monto;
      this.concepto = concepto;
   }

}