package com.htc.jbpm.reclamos;

import com.htc.jbpm.reclamos.ReclamoDTO

rule "set as fechaValida" ruleflow-group "reglaFechaCompra"
no-loop
when
	$p: ReclamoDTO(montoCompra > 18)
then 
	modify($p){
		setFechaCompraValida(true);
	}
end

rule "set as fechaInvalida" ruleflow-group "reglaFechaCompra"
no-loop
when
	$p : ReclamoDTO(montoCompra< 18)
then
	modify($p){
		setFechaCompraValida(false);
	}
end